# Generated by Django 4.2.11 on 2024-05-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_alter_appointment_doctor_alter_appointment_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboards.appointment'),
        ),
    ]
