# Generated by Django 4.2.11 on 2024-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_datetime',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
