# Generated by Django 4.2.11 on 2024-03-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_rename_appointment_datetime_appointment_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
