# Generated by Django 4.2.11 on 2024-03-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_alter_appointment_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end_time',
            new_name='oppo_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
