# Generated by Django 4.2.11 on 2024-03-26 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_rename_end_time_appointment_oppo_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='oppo_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='oppontement time'),
        ),
    ]
