version: '3.9'

services:
    # SmartCare service
    SmartCare:
        # Name of the image to be built
        image: smartcare

        # container name 
        container_name: smartcare_container

        # Build the image from the Dockerfile in the current directory
        build:
            context: .
            dockerfile: Dockerfile
        # Restart policy
        restart: unless-stopped

        # Port connect django to docker
        ports:
            - "8000:8000"

        # Volume mapping
        volumes:
            - .:/smartCareApp

        # Service dependencies
        depends_on:
            - db

        # Runtime command
        entrypoint: [ "./smartcare-entrypoint.sh" ]

    # db service
    db:
        # Name of the image to be pulled from Docker Hub.
        image: mysql:latest
        container_name: db_container

        # Port mapping
        ports:
            - "3306:3306"

        # database variables
        environment:
            MYSQL_ROOT_PASSWORD: smartcare
            MYSQL_DATABASE: smartcare
            MYSQL_PASSWORD: smartcare

        # Restart policy
        restart: unless-stopped

        # Volume mapping
        volumes:
            - db_data:/var/lib/mysql

# Volumes
volumes:
    # db_data volume definition
    db_data: