# Generated by Django 5.0.2 on 2024-04-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='patienttype',
            field=models.CharField(blank=True, choices=[('Not Registered', 'Not Registered'), ('Private', 'Private'), ('NHS', 'NHS')], max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.CharField(blank=True, choices=[('Master', 'Master'), ('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Dr', 'Dr')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
