# Generated by Django 5.0.2 on 2024-04-29 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0002_patient_name_patient_patienttype_patient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
